version: "3.8"

services:
  nginx-waf:
    image: owasp/modsecurity-crs:4.20.0-nginx-alpine-202511100111
    container_name: nginx-waf
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Tu sitio estático
      - ./html:/usr/share/nginx/html:ro

      # Config propia del sitio
      - ./nginx/conf.d:/etc/nginx/conf.d

      # Volúmenes compartidos con certbot
      - certbot-etc:/etc/letsencrypt:ro
      - certbot-www:/var/www/certbot

  certbot:
    image: certbot/certbot
    container_name: certbot
    # no expone puertos, solo usa volúmenes
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    entrypoint: sh
    command: -c "echo 'Certbot listo. Ejecutá manualmente el comando certbot...'"

volumes:
  certbot-etc:
  certbot-www:
