services:
  nginx-waf:
    image: owasp/modsecurity-crs:4.20.0-nginx-alpine-202511100111
    container_name: nginx-waf
    restart: unless-stopped
    environment:
      - PORT=8080          # puerto interno por defecto
      - SSL_PORT=8443      # (lo usaremos despu√©s)
      - SERVER_NAME=khrix.com.ar
    ports:
      - "80:8080"
      # M√°s adelante, cuando tengamos SSL: - "443:8443"
    volumes:
      - ./html:/usr/share/nginx/html:ro

      # üëá NUEVO: template de default.conf
      - ./nginx/default.conf.template:/etc/nginx/templates/conf.d/default.conf.template:ro

      # Vol√∫menes para certbot (para m√°s adelante)
      - certbot-etc:/etc/letsencrypt:ro
      - certbot-www:/var/www/certbot

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    entrypoint: sh
    command: -c "echo 'Certbot listo. Despu√©s ejecut√°s certbot manualmente.'"

volumes:
  certbot-etc:
  certbot-www:
