services:
  nginx-waf:
    image: owasp/modsecurity-crs:4.20.0-nginx-alpine-202511100111
    container_name: nginx-waf
    restart: unless-stopped
    environment:
      - PORT=8080          # puerto interno por defecto
      - SSL_PORT=8443      # (lo usaremos despu√©s)
      - SERVER_NAME=khrix.com.ar
      - SERVER_TOKENS=off
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - ./html:/usr/share/nginx/html:ro

      # üëá NUEVO: template de default.conf
      - ./nginx/default.conf.template:/etc/nginx/templates/conf.d/default.conf.template:ro

      # Vol√∫menes para certbot (para m√°s adelante)
      - certbot-etc:/etc/letsencrypt:ro
      - certbot-www:/var/www/certbot

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot

  keycloak:
    image: quay.io/keycloak/keycloak:latest   # o una versi√≥n concreta, ej: 26.0
    container_name: keycloak
    restart: unless-stopped
    environment:
      - KC_DB=dev-file
      - KC_HTTP_PORT=8080

      # MUY IMPORTANTE para proxy
      - KC_PROXY=edge
      - KC_PROXY_HEADERS=xforwarded

      # Keycloak colgado en /keycloak
      - KC_HTTP_RELATIVE_PATH=/keycloak

      # C√≥mo se ve hacia afuera
      - KC_HOSTNAME=khrix.com.ar
      - KC_HOSTNAME_STRICT_HTTPS=true

      # Admin
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin123

    command:
      - start-dev
    # No exponemos puertos al host, Nginx lo ve por la red interna de Docker

volumes:
  certbot-etc:
  certbot-www:
